name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.1.13"

      - name: Install project
        run: make install
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make test

      - name: Publish package on PyPi
        run: |
          poetry config http-basic.pypi __token__ ${{secrets.PYPI_TOKEN}}
          poetry build
          poetry publish

      - name: Publish GitHub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
